<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="1.989" tests="3" failures="1">
  <testsuite name="Root Suite" timestamp="2025-03-31T14:35:14" tests="0" file="e2e-testing/cypress/e2e/knowledge-test-page.cy.ts" time="0.000" failures="0">
  </testsuite>
  <testsuite name="Knowledge Page" timestamp="2025-03-31T14:35:14" tests="3" time="1.957" failures="1">
    <testcase name="Knowledge Page &quot;before each&quot; hook for &quot;should display the knowledge page with basic navigation elements&quot;" time="0.685" classname="&quot;before each&quot; hook for &quot;should display the knowledge page with basic navigation elements&quot;">
      <failure message="`cy.visit()` failed trying to load:

http://localhost:3000/knowledge

The response we received from your web server was:

  &gt; 500: Internal Server Error

This was considered a failure because the status code was not `2xx`.

If you do not want status codes to cause failures pass the option: `failOnStatusCode: false`

Because this error occurred during a `before each` hook we are skipping the remaining tests in the current suite: `Knowledge Page`" type="CypressError"><![CDATA[CypressError: `cy.visit()` failed trying to load:

http://localhost:3000/knowledge

The response we received from your web server was:

  > 500: Internal Server Error

This was considered a failure because the status code was not `2xx`.

If you do not want status codes to cause failures pass the option: `failOnStatusCode: false`

Because this error occurred during a `before each` hook we are skipping the remaining tests in the current suite: `Knowledge Page`
    at <unknown> (http://localhost:3000/__cypress/runner/cypress_runner.js:132351:76)
    at visitFailedByErr (http://localhost:3000/__cypress/runner/cypress_runner.js:131757:12)
    at <unknown> (http://localhost:3000/__cypress/runner/cypress_runner.js:132334:13)
    at tryCatcher (http://localhost:3000/__cypress/runner/cypress_runner.js:1777:23)
    at Promise._settlePromiseFromHandler (http://localhost:3000/__cypress/runner/cypress_runner.js:1489:31)
    at Promise._settlePromise (http://localhost:3000/__cypress/runner/cypress_runner.js:1546:18)
    at Promise._settlePromise0 (http://localhost:3000/__cypress/runner/cypress_runner.js:1591:10)
    at Promise._settlePromises (http://localhost:3000/__cypress/runner/cypress_runner.js:1667:18)
    at _drainQueueStep (http://localhost:3000/__cypress/runner/cypress_runner.js:2377:12)
    at _drainQueue (http://localhost:3000/__cypress/runner/cypress_runner.js:2370:9)
    at Async._drainQueues (http://localhost:3000/__cypress/runner/cypress_runner.js:2386:5)
    at Async.drainQueues (http://localhost:3000/__cypress/runner/cypress_runner.js:2256:14)
From Your Spec Code:
    at Context.eval (webpack:///./cypress/e2e/knowledge-test-page.cy.ts:22:0)]]></failure>
    </testcase>
  </testsuite>
</testsuites>